FROM registry.access.redhat.com/ubi8/ubi-minimal

ENV JDBC_URL=""
ENV JDBC_USERNAME=""
ENV JAEGER_HOST_PORT=""
ENV ZIPCODE_SERVICE_URL=""

WORKDIR /work/
COPY target/*-runner /work/application
RUN chmod 775 /work
EXPOSE 8080
CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]