version: "2"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    networks:
      - local_network
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    restart: unless-stopped
  city-service:
    image: city-service-quarkus:latest
    container_name: city-service
    environment:
      - ZIPCODE_SERVICE_URL=http://localhost:8080
      - JAEGER_HOST_PORT=jaeger
      - JDBC_URL=jdbc:tracing:h2:tcp://h2-database:1521/default
      - JDBC_DIALECT=org.hibernate.dialect.H2Dialect
      - JDBC_USERNAME=sa
    depends_on:
      - "jaeger"
      - "h2-database"
    links:
      - jaeger:jaeger
      - h2-database:h2-database
    networks:
      - local_network
    ports:
      - 8080:8080
    restart: unless-stopped
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    environment:
      - JOBS=city-service:8080
    depends_on:
      - "city-service"
    links:
      - city-service:city-service
    networks:
      - local_network
    ports:
      - 9090:9090
    restart: unless-stopped
  h2-database:
    image: oscarfonts/h2
    container_name: h2-database
    environment:
      - H2_OPTIONS=-ifNotExists
    networks:
      - local_network
    ports:
      - 1521:1521
      - 81:81

networks:
  local_network: